pom.xml
src/main/java/ch/heigvd/dil/App.java
src/test/java/ch/heigvd/dil/AppTest.java

Création du projet Maven

---

LICENSE

Ajout de la license du projet.

---

.gitignore
pom.xml

Ajout de Picocli au projet Maven

---

README.md

Création du readme

---

src/main/java/ch/heigvd/dil/Main.java
src/main/java/ch/heigvd/dil/subcommands/NewCmd.java

Creation de la sous-commande new

---

src/main/java/ch/heigvd/dil/Main.java
src/main/java/ch/heigvd/dil/subcommands/ServeCmd.java

Ajout de la sous-commande serve

---

src/main/java/ch/heigvd/dil/Main.java
src/main/java/ch/heigvd/dil/subcommands/BuildCmd.java

Création de la sous-commande build de picocli.

---

src/main/java/ch/heigvd/dil/Main.java
src/main/java/ch/heigvd/dil/subcommands/CleanCmd.java

Ajout de la sous-commande clean

---

portfolio.md

Création du portfolio

---

pom.xml
src/main/java/ch/heigvd/dil/Site.java
src/test/java/ch/heigvd/dil/SiteTest.java

Changement du nom de l'application

---

README.md
pom.xml
src/packaging/windows.bat

Closes #37 
Temps effectif : 40 minutes

Mise en place packaging

---

.github/workflows/pr-validation.yaml

Closes #34 
Temps effectif: 15'

Création du workflow pour l'intégration continue

---

pom.xml
src/main/java/ch/heigvd/dil/Site.java
src/main/resources/project.properties

Closes #29
Temps effectif : 2h30

La commande version est opérationnelle.

---

pom.xml
src/main/java/ch/heigvd/dil/Site.java
src/main/java/ch/heigvd/dil/subcommands/BuildCmd.java
src/main/java/ch/heigvd/dil/subcommands/CleanCmd.java
src/main/java/ch/heigvd/dil/subcommands/NewCmd.java
src/main/java/ch/heigvd/dil/subcommands/ServeCmd.java
src/main/java/ch/heigvd/dil/util/HTMLConverter.java
src/test/java/ch/heigvd/dil/SiteTest.java
src/test/java/ch/heigvd/dil/util/HTMLConverterTest.java

Closes #35 
Temps effectif: 20'

Mise en place de spotless

---

src/main/java/ch/heigvd/dil/util/HTMLConverter.java
src/main/java/ch/heigvd/dil/util/MarkdownValidator.java
src/main/java/ch/heigvd/dil/util/Tuple.java
src/main/java/ch/heigvd/dil/util/YAMLParser.java
src/test/java/ch/heigvd/dil/util/HTMLConverterTest.java
src/test/java/ch/heigvd/dil/util/MarkdownValidatorTest.java
src/test/resources/validator.txt

Création du validateur markdown/yaml et ses tests

---

README.md

Closes #52 
Closes #46 
Temps effectif: 75'

Ajout de la description de toute les commandes disponible sur le site

---

diagramme_classe.sly

Closes #61
Temps effectif : 80'

Création du diagramme de classe

---

.github/workflows/javadoc-creation.yaml
pom.xml

Closes #71
Temps effectif : 90'

Fb javadoc generation

---

pom.xml

Closes #72
Temps effectif: 25'

Implémentation de jacoco via maven terminée.

---

src/test/java/ch/heigvd/dil/util/TreeWatcherTest.java

Refactor des tests du TreeWatcher pour utiliser des wait/notify

---

src/main/java/ch/heigvd/dil/subcommands/BuildCmd.java
src/main/java/ch/heigvd/dil/subcommands/ServeCmd.java
src/test/java/ch/heigvd/dil/subcommands/BaseCmdTest.java
src/test/java/ch/heigvd/dil/subcommands/BuildCmdTest.java
src/test/java/ch/heigvd/dil/subcommands/ServeCmdTest.java

Ajout de test pour vérifier que le serveur fonctionne

---

src/main/java/ch/heigvd/dil/subcommands/BuildCmd.java
src/main/java/ch/heigvd/dil/subcommands/BuildableCmd.java
src/main/java/ch/heigvd/dil/subcommands/CleanCmd.java
src/main/java/ch/heigvd/dil/subcommands/InitCmd.java
src/main/java/ch/heigvd/dil/subcommands/ServeCmd.java
src/main/java/ch/heigvd/dil/util/SiteBuilder.java
src/main/resources/index.default.md
src/test/java/ch/heigvd/dil/subcommands/BaseCmdTest.java
src/test/java/ch/heigvd/dil/subcommands/BuildCmdTest.java
src/test/java/ch/heigvd/dil/subcommands/InitCmdTest.java
src/test/java/ch/heigvd/dil/subcommands/ServeCmdTest.java

Closes #65 
Temps effectif: 120'

Implémentation de l'option --watch pour la commande serve
